### ISSUE TITLE
Search soft deleted relations

### ISSUE THREAD

**Issue by preliot** [TitasGailius/nova-search-relations#13]
This package will nog search soft deleted related models. Default Nova behaviour allows this when you filter on 'include with deleted'. Would be nice to have this.

And thanks for this package, it works like a charme!

**Comment by itamas** [comment]
You have to modify the core trait of this package. The key function is applyRelationSearch(). 
Modified function:
`protected static function applyRelationSearch(Builder $query, string $search): Builder
    {
        foreach (static::searchableRelations() as $relation => $columns) {
            $query->orWhereHas($relation, function ($query) use ($columns, $search) {
                $query->where(static::searchQueryApplier($columns, $search))->withTrashed();
            })->withTrashed();
        }

        return $query;
    }`

**Comment by preliot** [comment]
But wouldn't that always search **with** trashed models? Nova lets you choose whether you search with or without.. Or am i mistaken?

**Comment by TitasGailius** [comment]
With the new release https://github.com/TitasGailius/nova-search-relations/pull/27, you may now extend the search for your custom needs.
