### ISSUE TITLE
Search concat of fields

### ISSUE THREAD

**Issue by blasto333** [TitasGailius/nova-search-relations#20]
Would be nice if we could do this
    
    public static $searchRelations = [
	    'athletes' => ['first_name','last_name','CONCAT(first_name," ",last_name)']
    ],

**Comment by TitasGailius** [comment]
I finally got some time to check this. I want the relationship search to behave exactly the same how Nova is behaving with regular search. This PR breaks this consistency.

If you want to adjust the behaviour to your needs, overriding this method is not of a big deal.
