### ISSUE TITLE
Search relations using other database connection

### ISSUE THREAD

**Issue by newtongamajr** [TitasGailius/nova-search-relations#22]
Hi @TitasGailius, first of all congratulation for this amazing package and to share it with us!
I'm using your package together with hyn/multitenant (https://github.com/tenancy/multi-tenant) that provides me a multitenant environment out-of-the-box. 
This environment is composed of a system database connection and the tenant database connection (its a multi-database tenant environment) and some tables that are shared among all tenants resides on system connection and when I try to access these relationships, I'm receiving the error messages logged on my Laravel logs, probably because nova-search-relations is not respecting the database connection informed on my system models.

[laravel-2020-03-06.log](https://github.com/TitasGailius/nova-search-relations/files/4300321/laravel-2020-03-06.log)

Best Regards!

**Comment by TitasGailius** [comment]
this package simply adds `whereHas(...)` constraint to the search query of your resource.

You can easily reprocude the same behaviour by doing something like this:

```php
User::whereHas('posts')->get();
```

This means this package 100% relies on Laravel's eloquent query builder.
