### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Enmaboya** [TitasGailius/nova-search-relations#3]
hi!
Is it possible to sort EVENTS by cities, which in turn are related to restaurants?
![default](https://user-images.githubusercontent.com/32259003/45487551-bd4d1b00-b76f-11e8-8d24-979412ea2b76.png)
something like that
    public static $searchRelations = [
        'restaurants' => 'city' => ['title'],
    ];

**Comment by TitasGailius** [comment]
You may set up a has many through relationship.
https://laravel.com/docs/5.7/eloquent-relationships#has-many-through
Then simply
```php
public static $searchRelations = [
    'cities' => ['title'],
];
```
