### ISSUE TITLE
Nested relationship search is broken in 2.0.0

### ISSUE THREAD

**Issue by odinns** [TitasGailius/nova-search-relations#31]
Nice package! 😊 

Trying out your package, I found that [nested relationship search](https://github.com/TitasGailius/nova-search-relations#nested-relationships) is broken in 2.0.0, as it returns `Call to undefined relationship [user.country]` now.

Works in 1.0.6 though.

**Comment by chancezeus** [comment]
Confirmed, the "ensureRelationshipExists" method in "RelationSearch" does not take into account nested relations

**Comment by chancezeus** [comment]
Tried a "quick fix", if you replace the current content (I run php8 so some changes might be required) with the following:
```php
        if (!str_contains($relation, '.')) {
            $query->getRelation($relation);
        }

        $parts = explode('.', $relation);
        $rel = $query;
        while(!empty($parts)) {
            $rel = $rel->getRelation(array_shift($parts));
        }
```

Then it will be able to resolve the nested relations

**Comment by brandonb927** [comment]
We just upgraded to v2.0 recently and got bit by this issue :(

**Comment by TitasGailius** [comment]
Fixed in https://github.com/TitasGailius/nova-search-relations/tree/2.0.1

**Comment by brandonb927** [comment]
Thank you @TitasGailius!
