### ISSUE TITLE
Question: throws has() and whereHas() do not support MorphTo relationships.

### ISSUE THREAD

**Issue by icaroce** [TitasGailius/nova-search-relations#5]
Hi.

Do you have workaround for this situation?

[https://github.com/laravel/framework/issues/25724](https://github.com/laravel/framework/issues/25724)

**Comment by TitasGailius** [comment]
Unfortunately no. As explained here https://github.com/laravel/framework/issues/18523 this is basically not fixable.

**Comment by dillingham** [comment]
@icaroce https://medium.com/laravel-nova/nova-morph-to-search-relations-2296dbb66906
