### ISSUE TITLE
Config for `applySearch()` to specif resource query?

### ISSUE THREAD

**Issue by justinmoh** [TitasGailius/nova-search-relations#6]
Appreciate your great work Titas.

Is it possible to change the implementation which could leverage Nova's existing resource query?

Searching through relation is handle, especially on Index page, but I don't see how I can turn it off at Global Search.

**Comment by TitasGailius** [comment]
Hey Justin,

good question, I'll try to investigate it and see if I can implement something like this.

**Comment by TitasGailius** [comment]
Global search improved in `1.0.4` release. https://github.com/TitasGailius/nova-search-relations/commit/1e7408a678b9258537cb15ceb58a56016501243a
