### ISSUE TITLE
Global search broken

### ISSUE THREAD

**Issue by desaintflorent** [TitasGailius/nova-search-relations#8]
Recently the search functionality broke on my nova app.
It seems that I need to declare $searchRelations for any model I have set  in nova.
If not, the global search ( or any search in a nova field ) display the error : "Access to undeclared static property: App\Nova\City::$searchRelations"

I'm using laravel  5.6.39 and Nova 1.2.1

**Comment by desaintflorent** [comment]
As a fix I currently do :
**public static $searchRelations = [];**
For any model in nova

**Comment by TitasGailius** [comment]
Tested it with Nova 1.2.1 and Laravel 5.6, everything works as expected.

Can you provide stacktrace or some more details on how to reproduce it?

**Comment by TitasGailius** [comment]
also which php version are you using?

**Comment by TitasGailius** [comment]
closing this for now.
